/**
* OOPSBannerApp UC2- BAnner Display Application
* this class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the 
* console using individual print statements for each line, creating a decorative text effect
*
* The banner is generated by printing predefined string patterns line by line ,
* where each line contributes to forming the letters O,O,P,S in a stylized format.
* This extends a basic user story by adding visual representation to a simple message output.
*
* @author Devoloper
* @version 2
*
*/
public class OOPSBannerAPP{
	public static void main(String[] args) {
		System.out.println("   ***   " + " " + "   ***   " + " " + "  ******  " + " " + "   ***** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "  **    **" + " " + "  ** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "  **     **" + " " + "** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "  **    **" + " " + "  ** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "  ******   " + " " + "  *** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "  **    " + " " + "        ** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "  **    " + " " + "         ** ");
		System.out.println("  ** ** " + " " + "   ** ** " + " " + "   **    " + " " + "        ** ");
		System.out.println("   *** " + " " + "     *** " + " " + "    **    " + " " + "   *****");
	}
}
	